export default function StatusPanel() {
  const registryAddress =
    process.env.NEXT_PUBLIC_REGISTRY_ADDRESS ?? "Not set";
  const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? "Not set";

  return (
    <div className="rounded-xl border bg-white p-6 shadow-sm space-y-4">
      <div>
        <h2 className="text-xl font-bold text-gray-900">System Status</h2>
        <p className="text-sm text-gray-700 mt-1">
          Demo configuration for the current xPilot environment.
        </p>
      </div>

      <div className="grid gap-3 sm:grid-cols-2">
        <div className="rounded-lg border bg-gray-50 p-4">
          <p className="text-xs uppercase tracking-wide text-gray-600">Mode</p>
          <p className="mt-1 font-semibold text-gray-900">
            AI Advisor / Local Demo
          </p>
        </div>

        <div className="rounded-lg border bg-gray-50 p-4">
          <p className="text-xs uppercase tracking-wide text-gray-600">
            Network
          </p>
          <p className="mt-1 font-semibold text-gray-900">
            Anvil Local (Chain ID 31337)
          </p>
        </div>

        <div className="rounded-lg border bg-gray-50 p-4 sm:col-span-2">
          <p className="text-xs uppercase tracking-wide text-gray-600">
            Registry Contract
          </p>
          <p className="mt-1 font-mono text-sm break-all text-gray-900">
            {registryAddress}
          </p>
        </div>

        <div className="rounded-lg border bg-gray-50 p-4 sm:col-span-2">
          <p className="text-xs uppercase tracking-wide text-gray-600">
            AI Engine
          </p>
          <p className="mt-1 font-mono text-sm break-all text-gray-900">{apiUrl}</p>
        </div>

        <div className="rounded-lg border bg-gray-50 p-4 sm:col-span-2">
          <p className="text-xs uppercase tracking-wide text-gray-600">
            Execution Model
          </p>
          <p className="mt-1 text-sm text-gray-800">
            Portfolios are generated by the AI advisor, then saved to the local
            onchain registry for demo validation. No user wallet connect or live
            market execution is enabled in this mode.
          </p>
        </div>
      </div>
    </div>
  );
}
